server:
  port: 9090

spring:
  h2:
    console:
      enabled: true

keycloak:
  realm: springdemo
  auth-server-url: http://localhost:8080/
  resource: springboot
  public-client: true
  bearer-only: true