server:
  port: 9090


spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

keycloak:
  realm: springdemo
  auth-server-url: http://localhost:8080/
  resource: springboot
  public-client: true
  bearer-only: true

date:
  api: http://date.jsontest.com/

weather:
  api: http://api.weatherstack.com/current?access_key=1efaeb389c49f8dfb8003ebf3d954291&query=
