server:
  port: 9090


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Raju@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


keycloak:
  realm: springdemo
  auth-server-url: http://localhost:8080/
  resource: springboot
  public-client: true
  bearer-only: true

date:
  api: http://date.jsontest.com/

weather:
  api: http://api.weatherstack.com/current?access_key=1efaeb389c49f8dfb8003ebf3d954291&query=
